### ISSUE TITLE
Non-default type worlds can randomly switch to default worlds

### ISSUE THREAD

**Issue by SunSeeker-02** [SkyDeckAGoGo/bta-issues#103]
Version: 1.7.6.1
This happened to me literally as I was playing on the world. This seems to happen at complete random, so I assume it has to do with the way chunks are stored in the data.

![2022-02-24_21 44 28](https://user-images.githubusercontent.com/100394372/155644008-e3191d81-e0d1-43e6-a2a9-e4d8871a8ac4.png)

As you can see in the picture, the world was generated as Extended Default, but has become simply Default (the clouds are at Default level).

**Comment by Joe4422** [comment]
Have you built a Nether portal in your world yet?

**Comment by bestsoft100** [comment]
How to reproduce:

Create New World
Go to Nether
Restart Game
Exit Nether
Leave World

**Comment by bestsoft100** [comment]
Fixed in https://github.com/SkyDeckAGoGo/minecraft-bta/commit/d49012460a6a3d4de4a2ddd9da1870dffb037140
