### ISSUE TITLE
Cannot override controller input with a mouse

### ISSUE THREAD

**Issue by SkyDeckAGoGo** [SkyDeckAGoGo/bta-issues#105]
e.g. should be able to access menu items with a mouse while controller mode is enabled, lack of this can cause the player to lock themselves out of the game if they enabled controller mode and do not have a controller on hand

**Comment by SkyDeckAGoGo** [comment]
Apparently doesn't work on betacraft, DIAMOND#8428 and Kаy#4430 were getting issues

**Comment by bestsoft100** [comment]
fixed in pre 2
