### ISSUE TITLE
Cannot dye label brown

### ISSUE THREAD

**Issue by Cosmic306** [SkyDeckAGoGo/bta-issues#108]
**Description**
It is impossible to dye a label brown, as upon combining a label with cocoa beans in the crafting menu, nothing happens.

**To Reproduce**
1. Put cocoa beans and a label in the crafting menu.
2. Witness lack of result.

**Expected behavior**
Upon combining cocoa beans with a label in the crafting menu, it should've given you a new label that would allow you to give an entity a brown nickname.

**Screenshots**
![2022-02-26_22 10 41](https://user-images.githubusercontent.com/100500775/155866607-44f1cdd9-d142-49f0-9c4e-47425f4c2907.png)

**Version**
1.7.6.2 pre-release 1

**Comment by LukeisStuff** [comment]
Fixed in 1.7.6.2
