### ISSUE TITLE
Lamps don't get powered when they should

### ISSUE THREAD

**Issue by Dorikobac** [SkyDeckAGoGo/bta-issues#129]
**Describe the bug**
Redstone lamps don't get powered on by redstone that is passing through blocks. If you don't already know, in redstone, when you send power into a block, all blocks touching it should also get powered. Not having this option makes working with these redstone lamps really hard and limited, they can not be used nearly as easily as vanilla redstone lamps. 

**To Reproduce**
1. Open a creative world, and place down lamps.
2. Try to power them by placing redstone torches next to them or by passing a redstone signal through a block using a repeater.
3. See error

**Expected behavior**
When I send a redstone signal into a lamp, I expect all lamps next to it to turn on.
When I send a redstone signal into a block that has a lamp next to it, I expect the lamp to turn on.
When I place a redstone torch or a lever next to a lamp, I expect the lamp to turn on.

**Screenshots**
[https://pasteboard.co/mEUjpJRiNUDH.png](url)

**Version info**
 - Version 1.7.6.2

**Additional context**
I believe this is an unintended bug and not the way you actually want lamps to work, if not, then consider this a suggestion? because I don't think the current state is the better one lol

**Comment by SkyDeckAGoGo** [comment]
fix implemented for 1.7.6.2_01
