### ISSUE TITLE
Dash Boots Readdition

### ISSUE THREAD

**Issue by Bloxxel64** [SkyDeckAGoGo/bta-issues#145]
I would love to see the Dash Boots properly implemented. Here's how they can work.

Press the spacebar while in the air, and you will dash in the direction you are looking. Once you use your dash, you cannot use it again until you touch the ground. You can get a version of the boots called the Double-Dash Boots to have 2 dashes. If you jump as soon as you touch the ground after a dash, you preserve the momentum from the dash, thus allowing you to wavedash.

**Comment by Joe4422** [comment]
Thanks for the suggestion! The Dash Boots will almost certainly be re-added, but not until 1.7.8 when we start working on Paradise.
