### ISSUE TITLE
Automatic fog changing based on season & weather

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [SkyDeckAGoGo/bta-issues#154]
While playing I've found that it helps add to the atmosphere if I change my fog setting to be thin during summer, then slowly thicken into winter, then thin again through spring, as well as bringing fog 1/2 closer during rain and snow. Would be cool to see this as a proper feature rather than requiring pressing F a bunch of times every few hours.

**Comment by SpazoTron12** [comment]
There is such a thing as foggy weather ingame already

**Comment by AustraliaIsMyCity** [comment]
ya but i want my rain and snow to be foggy

**Comment by Joe4422** [comment]
That already exists - rain, snow and thunder all increase the amount of fog depending on the intensity and power of the current weather event.

**Comment by Joe4422** [comment]
Closed as this issue is already implemented.
