### ISSUE TITLE
Move to string IDs to completely stop common ID conflicts

### ISSUE THREAD

**Issue by pkstDev** [SkyDeckAGoGo/bta-issues#155]
**Is your feature request related to a problem? Please describe.**
No I guess

**Describe the solution you'd like**
Move to string IDs to completely stop common ID conflicts, like what Mojang did in 1.13

**Describe alternatives you've considered**
Dynamically expand the ID limit?
And also it would be great if you add a napespace system

**Additional context**
~~my english is poor www~~

**Comment by Joe4422** [comment]
This is already being worked on for 1.7.7.0.
