### ISSUE TITLE
Gunpowder crafting recipe

### ISSUE THREAD

**Issue by Dusan000** [SkyDeckAGoGo/bta-issues#160]
I want more TNT but I don't like creeper farms, so I think being able to craft gunpowder would be really helpful.

Ingredients: Charcoal, Sulfur and Saltpeter
  -Sulfur is obtained from ores underground
  -Saltpeter is obtained by dropping manure into a water-source block. The manure disappears, the water evaporates and a Saltpeter item-drop is left behind.

**Comment by MeowPi** [comment]
haha indeed

**Comment by MeowPi** [comment]
> ah yes, add shit(manure) to bta

Yep, thats litterally what this person is requesting.
