### ISSUE TITLE
ghast and creeper expansion animations don't play in multiplayer

### ISSUE THREAD

**Issue by SkyDeckAGoGo** [SkyDeckAGoGo/bta-issues#18]
Creepers and Ghasts expand when attacking in singleplayer. In multiplayer, this functionality is lost.

**Comment by LukeisStuff** [comment]
Partially fixed as of 1.7.6.2, Creepers have their animation but ghasts dont

**Comment by LukeisStuff** [comment]
Closing as #66 exist and this is partially fixed
