### ISSUE TITLE
Any mouse click makes the game pauses while not in a menu/inventory

### ISSUE THREAD

**Issue by tomast1337** [SkyDeckAGoGo/bta-issues#192]
**Describe the bug**
Any mouse click makes the game pauses while not in a menu/inventory, If i play the game holding the Escape key i can use de mouse "normally", maybe it's something with LWJGL?

**How to Reproduce**
1. Load any save 
2. Click mouse left or right button

**Expected behavior**
Register a mouse left or right click in the game

**Screenshots**
Not applicable

**Version info (please complete the following information):**
 - BTA_1.7.6.2_02.MultiMC

**Additional context**

Java Version:
- openjdk version "1.8.0_332"

LWJGL:
-LWJGL 2 version 2.9.4-nightly-20150209

PC specs:
- OS: Arch Linux x86_64 
- Kernel: 5.18.7-zen1-1-zen 
- DE: GNOME 42.2 
- CPU: AMD Ryzen 9 5950X (32) @ 3.400GHz 
- GPU: AMD ATI Radeon RX 580
- Memory: 15895MiB 

**Crash Logs**
Not applicable

**Comment by Apollointhehouse** [comment]
Try press F3 + P

**Comment by tomast1337** [comment]
> Try press F3 + P
thank you, that fixes the problem
