### ISSUE TITLE
Colours are completely wrong

### ISSUE THREAD

**Issue by nitrogenfive** [SkyDeckAGoGo/bta-issues#194]
<img width="966" alt="Screen Shot 2022-08-01 at 7 09 07 am" src="https://user-images.githubusercontent.com/105533515/182049053-6282ceeb-0387-4864-8cae-bedd5b6eb84f.png">
<img width="966" alt="Screen Shot 2022-08-01 at 7 08 17 am" src="https://user-images.githubusercontent.com/105533515/182049057-0befe6c4-a10e-4738-9ba8-1a26656e9b5a.png">
<img width="966" alt="Screen Shot 2022-08-01 at 7 07 02 am" src="https://user-images.githubusercontent.com/105533515/182049061-b74c98ba-224f-4f65-ab9a-a43832742d99.png">

latest.log: https://mclo.gs/BCJqjuF

Running on MacOS 12.5. M1 Macbook Air (2020), using Zulu Java 8.

**Comment by Joe4422** [comment]
Fixed for release 1.7.7.0.
