### ISSUE TITLE
Nether Portal portal block is a solid blue color as well as fire rendering as "Fire Test" or something along those lines.

### ISSUE THREAD

**Issue by PapaChinoPizza** [SkyDeckAGoGo/bta-issues#197]
**Describe the bug**
Nether portal portal block rendering as a blue texture and fire is rendering as "Fire Test" when a block is lit.

**To Reproduce**
1. Light a nether portal
2. Light something on fire with a flint and steel

**Expected behavior**
Textures rendering correctly

**Screenshots**
![unknown](https://user-images.githubusercontent.com/70350789/182107404-7e8dff9a-abe9-43f3-8736-7403a7b16a89.png)

**Version info (please complete the following information):**
- Version 1.7.6.2_02

**Comment by Joe4422** [comment]
If you go to Options > Video Settings > Visuals, what's Animations set to? If it's not set to Custom or Procedural you should expect to see this.
