### ISSUE TITLE
Black Screen on opening

### ISSUE THREAD

**Issue by Maboi000** [SkyDeckAGoGo/bta-issues#201]
**Describe the bug**
After installing the Client Jar with Betacraft when I open the BTA version, its just shows a black screen, it has been like this for more then an hour so it can't be loading.

**To Reproduce**
1. Go to 'https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/3106066-better-than-adventure-for-beta-1-7-3-timely
2. Download Betacraft, do the steps needed for installing it
3. See error

**Expected behavior**
Not load, and be stuck on a blackscreen which also cannot be closed normally unless forced through task manager

**Version info (please complete the following information):**
 - Version 1.7.6.2

**Comment by StarZenno** [comment]
Same error for me. I can play normally with default version selected by Betacraft. Cannot play with when BTA version is selected.

**Comment by Apollointhehouse** [comment]
try using MultiMC

**Comment by Maboi000** [comment]
> 

Can't use MultiMC cuz windows have fucked my paid version of MC and i lost more then 60+$ of payment for stoneworks. I won't ever play their game again
Ence why i'm using something other then MultiMC

**Comment by jonkadelic** [comment]
Download the latest version of BetaCraft and try again - there's been a new update that improves the mod repository, so install  BTA via that.

**Comment by Quiel245** [comment]
> > 
> 
> Can't use MultiMC cuz windows have fucked my paid version of MC and i lost more then 60+$ of payment for stoneworks. I won't ever play their game again Ence why i'm using something other then MultiMC

You can use UltimMC then if you want

**Comment by forkiesassds** [comment]
> > > 
> > 
> > 
> > Can't use MultiMC cuz windows have fucked my paid version of MC and i lost more then 60+$ of payment for stoneworks. I won't ever play their game again Ence why i'm using something other then MultiMC
> 
> You can use UltimMC then if you want

Please do not discuss about how you could commit piracy here. BTA developers do not support piracy.

**Comment by Quiel245** [comment]
> > > > 
> > > 
> > > 
> > > Can't use MultiMC cuz windows have fucked my paid version of MC and i lost more then 60+$ of payment for stoneworks. I won't ever play their game again Ence why i'm using something other then MultiMC
> > 
> > 
> > You can use UltimMC then if you want
> 
> Please do not discuss about how you could commit piracy here. BTA developers do not support piracy.

Oh, sorry... I though it was ok cuz he was using betacraft before
