### ISSUE TITLE
Textures changing randomly

### ISSUE THREAD

**Issue by falconfruitpunch1** [SkyDeckAGoGo/bta-issues#205]
It is likely that this has already been reported, but I haven't found it if so.

**Describe the bug**
Textures will, seemingly at random, lose pixels or gain new ones. I have attached images depicting this, from the creative inventory as well as held by my character. This is only happening to items, while blocks and block items seem fine.

**To Reproduce**
Unfortunately, I haven't really found one cause for this. I've been running the game for a while in creative, using commands to change my gamemode and the season. I am not using any resource packs, and this is my first time launching the game. Since this is only happening to a few items, I can't say for certain when this started. However, I adjusted my gamma settings, used F1 view a few times, and switched from the nether to the overworld.

**Expected behavior**
I expected the textures to look as they typically do in game.

**Screenshots**

![image](https://user-images.githubusercontent.com/85251532/183271824-c9a712c5-9405-4014-beb4-1b0b178fbafc.png)

<img width="529" alt="wacktextures" src="https://user-images.githubusercontent.com/85251532/183271834-c01f71cd-ca42-4b09-9179-b4b2657da550.PNG">

![2022-08-06_21 57 30](https://user-images.githubusercontent.com/85251532/183271845-4a06386b-e1dd-4b42-89ac-f19e6ffad251.png)

**Version info (please complete the following information):**
I am playing on version 1.7.6.2_02, using MultiMC.

**Additional context**
This is my first time launching the game. I have had the game open for over 3 hours in a single world, testing features out. This bug was not present at the beginning of the world, and I am only just now noticing it.

**Comment by Joe4422** [comment]
Could you detail your PC specifications? This has never been reported before, and at a glance it seems like it may be an issue with your GPU.

**Comment by falconfruitpunch1** [comment]
![image](https://user-images.githubusercontent.com/85251532/183272087-dc2bed22-9b14-4fe7-a01e-cd0ecc759e41.png)
not really sure what specs to post, sorry! i dont do this a lot

**Comment by Joe4422** [comment]
It would be useful to know which GPU you have - can you post your F3 screen?

**Comment by falconfruitpunch1** [comment]
![2022-08-06_22 12 46](https://user-images.githubusercontent.com/85251532/183272126-42878728-11a9-4a13-8067-361ea5cb5d40.png)
certainly!

**Comment by Joe4422** [comment]
Odd, I have the same GPU and I don't see this issue. Try updating your driver's via GeForce experience - the latest is 516 and you're running 515.

**Comment by falconfruitpunch1** [comment]
Working on this now, but the issue fixed itself when I restarted the game. Creating new worlds did not help this, so I'm really still not sure what caused it.

**Comment by falconfruitpunch1** [comment]
Update: Still can't reproduce the issue, don't know whether to keep this open or not though considering it worked itself out for me.
