### ISSUE TITLE
BTA on arch linux using polymc crashing

### ISSUE THREAD

**Issue by reisscake** [SkyDeckAGoGo/bta-issues#206]
PolyMC version: 1.4.1

Launched instance in offline mode

Minecraft folder is:
/home/maya/.local/share/PolyMC/instances/BTA.MultiMC.Updater/.minecraft

Java path is:
/usr/lib/jvm/java-8-openjdk/jre/bin/java

Checking Java version...
Java is version 1.8.0_345, using 64 (amd64) architecture, from Oracle Corporation.

Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
Intel Corporation WhiskeyLake-U GT2 [UHD Graphics 620] (rev 02)

DeviceName: VGA

Subsystem: ASUSTeK Computer Inc. Device 1981

OpenGL version string: 4.6 (Compatibility Profile) Mesa 22.1.4

Main Class:
  

Native path:
  /home/maya/.local/share/PolyMC/instances/BTA.MultiMC.Updater/natives

Libraries:
  /home/maya/.local/share/PolyMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /home/maya/.local/share/PolyMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /home/maya/.local/share/PolyMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /home/maya/.local/share/PolyMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /home/maya/.local/share/PolyMC/instances/BTA.MultiMC.Updater/libraries/customjar-1.jar

Native libraries:
  /home/maya/.local/share/PolyMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar
  /home/maya/.local/share/PolyMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar

Params:
  

Window size: 854 x 480

Java Arguments:
[-Xms512m, -Xmx4096m, -Duser.language=en]

Minecraft process ID: 10894

Aug 07, 2022 6:03:09 PM org.polymc.EntryPoint listen
SEVERE: Exception caught from launcher.
java.lang.UnsupportedOperationException
	at java.util.AbstractList.add(AbstractList.java:148)
	at java.util.AbstractList.add(AbstractList.java:108)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:162)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)

Aug 07, 2022 6:03:09 PM org.polymc.EntryPoint main
INFO: Exiting with 1
Process exited with code 1.

I am using java 8, I also have tried it with java 17 but it came out with the same error. I'm not sure what's wrong, 
![image](https://user-images.githubusercontent.com/102161059/183300107-8ebe888d-b002-46f8-917e-126274801d03.png)

**Comment by Tryzen-0** [comment]
for me it also crashes but im presented with a segmentation fault

**Comment by forkiesassds** [comment]
Update to 1.4.1, the issue has been fixed.
