### ISSUE TITLE
I'm don't launch game

### ISSUE THREAD

**Issue by Klayeryt** [SkyDeckAGoGo/bta-issues#208]
I went through betacraft and the black screen did everything according to the instructions
![Desktop Screenshot 2022 08 08 - 12 45 11 67](https://user-images.githubusercontent.com/90210691/183357098-b2781a92-bf1a-4f8e-9506-0819061bae28.png)

**Comment by Apollointhehouse** [comment]
Try MultiMC

**Comment by xIcee** [comment]
Try changing your Java instance. You may be using 17/18, but the game doesn't run with newer Java versions. Java 8 is reccomended.
