### ISSUE TITLE
[BUG] Full Crash While Exploring Dungeon

### ISSUE THREAD

**Issue by Miiiiika** [SkyDeckAGoGo/bta-issues#209]
Was exploring one of the new dungeons when the game seemingly crashed at random. Was just walking around and the game suddenly displayed a loading screen that said "saving chunks", and when the bar filled up went to a white screen that didn't go away until I closed the game. When I loaded back into the world I was in the same spot I was in when I crashed, did not crash again. Attached video shows the crash happening

https://user-images.githubusercontent.com/110947116/183782225-53998ce3-47d5-4b19-b6b2-e50d652f8751.mp4

**Comment by jonkadelic** [comment]
How much RAM have you allocated the game?

**Comment by Miiiiika** [comment]
> How much RAM have you allocated the game?
The default amount on the launcher, which I believe is 1024mb.

**Comment by jonkadelic** [comment]
Try upping it to 2048 and you shouldn't see any issues. If you get an error when launching after that, make sure your Java is 64-bit.

**Comment by Miiiiika** [comment]
Thanks
