### ISSUE TITLE
Mod Crashes on Startup (MultiMC)

### ISSUE THREAD

**Issue by ustayussuf** [SkyDeckAGoGo/bta-issues#213]
**Describe the bug**
MultiMC version of the mod crashes on startup

**To Reproduce**
1.  Open the mod on MultiMC
2. Minecraft crashes

**Expected behavior**
Minecraft should open

**Screenshots**
![image](https://user-images.githubusercontent.com/56765276/184557759-2030f6c9-ccd5-471f-ab74-98f81c0d9b5e.png)
![image](https://user-images.githubusercontent.com/56765276/184557763-86505dd7-db04-4d4b-a793-863e1aa7260c.png)

**Version info:**
 - Version 1.7.6.2_02

**Additional context**
Java Version: 1.8.0_341
Allocated Memory to Java: 1024 MB
System Info: [DxDiag.txt](https://github.com/SkyDeckAGoGo/bta-issues/files/9334242/DxDiag.txt)

**Crash Logs**
https://paste.ee/p/A6yGA

**Comment by bestsoft100** [comment]
Try updating your graphics driver

**Comment by forkiesassds** [comment]
Use a better JRE such as Azul or Eclipse Adoptium.

**Comment by ustayussuf** [comment]
> Try updating your graphics driver

Updated them game's still crashing

**Comment by ustayussuf** [comment]
> Use a better JRE such as Azul or Eclipse Adoptium.

tried both game's still crashing

**Comment by Quiel245** [comment]
I had the same problem before, to fix fhis you need an specific version of java, i found the solution here:
https://github.com/MultiMC/Launcher/wiki/Unsupported-Intel-GPUs

**Comment by ustayussuf** [comment]
> I think i had the same problem before, to fix this you need an specific version of java, i found the solution here: https://github.com/MultiMC/Launcher/wiki/Unsupported-Intel-GPUs

THANK YOU it works now
