### ISSUE TITLE
Huge black bars appear when launching on a 21:9 (and possibly any ultrawide) monitor

### ISSUE THREAD

**Issue by kanpov** [SkyDeckAGoGo/bta-issues#237]
**Version**: 1.7.6.2_02 (installed via MultiMC instance)
**Description**: This happens when launching the game with BTA on my 21:9 monitor (3440x1440), making it pretty much unplayable:
![image](https://user-images.githubusercontent.com/71177577/211196761-4b8f8afb-23e0-4495-8ce8-f5332dd336fa.png)
**Steps to Reproduce**: download MultiMC instance zip, import the instance via MultiMC, launch the game, look at this monstrosity. Note that this does not happen with a regular Minecraft instance, the bug does not go away after re-launching.

**Comment by kanpov** [comment]
got real and figured out that this can be fixed.

**Comment by forkiesassds** [comment]
That's actually an issue with HiDPI caused by applets not supporting HiDPI, they do have a solution in the works, but it causes more issues than it fixes. A proper solution would be to remove applets all together
