### ISSUE TITLE
Fog is way too close on one specific server and nowhere else

### ISSUE THREAD

**Issue by planet-man38** [SkyDeckAGoGo/bta-issues#244]
**Describe the bug**
Fog is about four times as close as it's supposed to on one specific server for me, and nowhere else. No one has been on that server to see the bug for themselves after it happened so I don't know if it happens to anyone else. The actual render distance is correct. Thanks to the fog being in general stupid, I can see the actual chunks going as far as they're supposed, it's just the fog for some reason.

**To Reproduce**
Literally no clue. It happens nowhere else and I have zero idea of what causes this but it's really annoying!

**Expected behavior**
The fog acts consistently everywhere and also would be nice if the fog wasn't right up to my face

**Screenshots**
These screenshots picture the fog when render distance is set to tiny and when it is set to extreme respectively.
![2023-01-14_18 49 47](https://user-images.githubusercontent.com/64433486/212488388-121f6a50-0a84-4619-b056-98c5e000a9be.png)
![2023-01-14_18 49 54](https://user-images.githubusercontent.com/64433486/212488391-2e973ef7-079b-4a9c-b7f6-47d3160e1a3d.png)

**Version info (please complete the following information):**
 - Version 1.7.6.2_02

**Additional context**
It doesn't happen anywhere outside of that server, not even on singleplayer it happens literally nowhere other than that very server. If whichever developer reviews this wants to know any context about what's on the server or wants to join the server, it is public. The server in question is Peanut BTA listed by the owner on the #servers channel

**Crash Logs**
The game didn't crash

this better not be some stupid feature, because if it is, I sincerely hope it gets removed and never even considered ever again.

**Comment by jonkadelic** [comment]
The weather is foggy.

**Comment by planet-man38** [comment]
So it is some stupid-ass feature bro what the fuck

**Comment by pkstDev** [comment]
do not be rude
it is pretty much a great feature, i dont find it anything wrong

**Comment by planet-man38** [comment]
So here's everything wrong with is:
It's confusing
It's annoying
It's hard to tell that it's a feature
It's pointless
I'm curious to hear if anyone at all asked for it
It's so rare that it feels like a bug
It worsens the experience for when it's active so good luck if you wanted to explore while it exists, because you won't be able to find anything because of it and all you have to do it wait (I sure do love waiting in video games)
I can't think of anything more because I've already wasted enough of my time on this utterly pointless bug report.

**Comment by LukeisStuff** [comment]
In the screenshot you sent it tells you what weather it is in the top left how is it hard to tell its a feature?

**Comment by planet-man38** [comment]
that's fair
I don't usually look at that but yeah that makes sense.
Doesn't mean I like it anymore, I still despise it
