### ISSUE TITLE
Chunk Error

### ISSUE THREAD

**Issue by VictoBe** [SkyDeckAGoGo/bta-issues#249]
I was wandering in my world and just found out that my generated chunks are very up high, while the others bellow.

**Screenshots**

![image](https://user-images.githubusercontent.com/124534329/216849029-17999a84-5cd2-405f-8de0-f532fb3fcd2c.png)

![image](https://user-images.githubusercontent.com/124534329/216849052-a81311fb-b970-43f0-b5cf-7a42d609e0fc.png)

The version in question **1.7.6.2**

Edit: also sometimes when I'm walking in the places below the higher chunks the frames just drops, it also happens when I do an certain action, like hitting a mob.

**Comment by jonkadelic** [comment]
This is due to a long standing issue with BTA where your world type will reset to Default after leaving the Nether. This has (hopefully) been resolved in the upcoming 1.7.7.0 release, which will store dimension information in its own data files.
