### ISSUE TITLE
Sometimes redstone torches don't activate lamps

### ISSUE THREAD

**Issue by SkyDeckAGoGo** [SkyDeckAGoGo/bta-issues#28]
related images https://cdn.discordapp.com/attachments/866992511725994006/922260594055323648/unknown.png
https://cdn.discordapp.com/attachments/866992511725994006/922260594294390834/2021-12-19_18.51.58.png

**Comment by LukeisStuff** [comment]
https://github.com/SkyDeckAGoGo/bta-issues/issues/129
