### ISSUE TITLE
World Hole Fix causes Connection Issues

### ISSUE THREAD

**Issue by Joe4422** [SkyDeckAGoGo/bta-issues#29]
Chunks will frequently fail to appear to the client in multiplayer sessions

**Comment by LukeisStuff** [comment]
Fixed with World Hole Fix Option

**Comment by bestsoft100** [comment]
is this fixed?

**Comment by SkyDeckAGoGo** [comment]
partially. still going to look into it but the setting at least gives people the option to avoid it
