### ISSUE TITLE
Moss burning sometimes destroys the entire block

### ISSUE THREAD

**Issue by LukeisStuff** [SkyDeckAGoGo/bta-issues#45]
When a mossy stone block is on fire sometimes it burns the moss off and sometimes the entire block burns

1. Place mossy stone block
2. Light on fire
3. Wait for it to burn away

The moss should burn off leaving the normal block behind

![image](https://user-images.githubusercontent.com/92662759/153734777-45ca421a-65d9-407e-a901-96aef8eacd6b.png)

![image](https://user-images.githubusercontent.com/92662759/153734789-dd1cedf2-ff0b-42e6-904f-3f85ff1901d5.png)

1.7.6.1

**Comment by bestsoft100** [comment]
Fixed
