### ISSUE TITLE
Mossy Cobblestone and Mossy Stone Bricks cannot burn

### ISSUE THREAD

**Issue by LukeisStuff** [SkyDeckAGoGo/bta-issues#46]
Mossy cobblestone and mossy stone bricks cannot burn and this means you cant burn the moss off like on mossy stones

1. Place mossy cobblestone and mossy stone bricks
2. Set them on fire
3. Wait for fire to go away

They should burn and remove the moss

![image](https://user-images.githubusercontent.com/92662759/153734923-30d32440-14c4-47af-9a6f-4df1fe93bbfe.png)

![image](https://user-images.githubusercontent.com/92662759/153734941-23e62f53-1f25-45a2-b272-7ef42e3dc951.png)

1.7.6.1

**Comment by bestsoft100** [comment]
Fixed in 1.7.6.2
