### ISSUE TITLE
Mossy oak logs cannot be smelted into charcoal

### ISSUE THREAD

**Issue by LukeisStuff** [SkyDeckAGoGo/bta-issues#57]
Mossy oak logs cannot be smelted into charcoal in a furnace or blast furnace

**To Reproduce**
1. Smelt mossy oak log in furnace
2. See error

The mossy oak logs should smelt into 1 charcoal 

![image](https://user-images.githubusercontent.com/92662759/153738866-fd930c55-4e2a-43b8-878a-4fca1ba1e9d0.png)

1.7.6.1

**Comment by bestsoft100** [comment]
fixed
