### ISSUE TITLE
Incorrect description on Clay Brick Stairs

### ISSUE THREAD

**Issue by LukeisStuff** [SkyDeckAGoGo/bta-issues#58]
The description for the Clay brick stairs is incorrect 

**To Reproduce**
1. Read description on Clay Brick Stairs
2. See error

Correct description:
Clay Brick block used for rapid vertical movement.

![image](https://user-images.githubusercontent.com/92662759/153738899-4b5bb04f-4ced-43e0-834a-92987a1639c5.png).

1.7.6.1

**Comment by bestsoft100** [comment]
That's every stair description

**Comment by LukeisStuff** [comment]
It says Brick block instead of CLAY Brick block

**Comment by bestsoft100** [comment]
fixed
