### ISSUE TITLE
Crash report doesn't appear when renderer crashes game

### ISSUE THREAD

**Issue by bestsoft100** [SkyDeckAGoGo/bta-issues#61]
**Describe the bug**
Crash report doesn't appear when renderer crashes game

**To Reproduce**
Crash game (for example like this: https://github.com/SkyDeckAGoGo/bta-issues/issues/60)

**Expected behavior**
Crash report appears

**Screenshots**
![image](https://user-images.githubusercontent.com/49400900/153780247-a775b6a0-b8b8-41cb-b63a-2b8ca156a60d.png)
No Crash Report!

**Version info (please complete the following information):**
1.7.6.1

**Additional context**
Windows 10
MultiMC

**Comment by Joe4422** [comment]
I'm somewhat skeptical that this is fixable given that you kind of need the renderer to render the crash UI, but good luck regardless

**Comment by bestsoft100** [comment]
watch this

**Comment by bestsoft100** [comment]
fixed
