### ISSUE TITLE
Breaking TNT with fire striker causes item drop and light

### ISSUE THREAD

**Issue by LukeisStuff** [SkyDeckAGoGo/bta-issues#64]
**Describe the bug**
When you break TNT with a fire striker it lights the tnt and drops it as an item which means infinite tnt

**To Reproduce**
1. In survival place a tnt and punch with fire striker
2. stand near and you can collect the drop 
3. See error

**Expected behavior**
Tnt is lit and it doesnt drop an item

**Screenshots**
![image](https://user-images.githubusercontent.com/92662759/153794711-ab92c2c3-9de8-4973-8308-186641af0224.png)

**Version info (please complete the following information):**
1.7.6.1

**Comment by bestsoft100** [comment]
fixed
