### ISSUE TITLE
Flamethrowers 

### ISSUE THREAD

**Issue by ehpep** [SkyDeckAGoGo/bta-issues#94]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by SkyDeckAGoGo** [comment]
Closed due to lack of detail. Don't use this place for spitballing please

**Comment by ehpep** [comment]
it was a joke, i immediately closed the issue after posting.

**Comment by LukeisStuff** [comment]
> it was a joke, i immediately closed the issue after posting.

Wow that was so funny
